logging:
  level:
  ############################### 配置输出sql #############################
    com.worhard.study.dao.mapper: debug

spring:
  ############################### 配置 mysql ##############################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luowen?serverTimezone=UTC
    username: root
    password: root
  ############################### 配置 redis ##############################
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456



mybatis:
  ############################### Mybatsi 扫描路径 #########################
  mapper-locations: classpath*:Mapper/*.xml
